name: Feature Request
description: File a feature request
title: "[Feature]: (Please note that the title must be in English)"
assignees:
  - misyaguziya
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: expect-to-happened
    attributes:
      label: Expect to happened
      description: What happened, and what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A feature I have expected ..."
    validations:
      required: true
  - type: dropdown
    id: expected-app-version
    attributes:
      label: Expected APP Version
      description: What version of App did you expect?
      options:
        - next newest version
        - a future version
    validations:
      required: true
  - type: dropdown
    id: expected-runtime-environment
    attributes:
      label: Expected Runtime Environment
      description: What runtime environment(OS) did you expect?
      options:
        - "Windows 10"
        - "Windows 11"
        - "Other"
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: Country/Region
      description: What Country(Region) did you expect?
      placeholder: Tell us what you see!
      value: "Qatar(example)"
    validations:
      required: true
  - type: textarea
    id: expected-output
    attributes:
      label: Expected Output
      render: sh
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Sharing features in images"
      value: |
        ![DESCRIPTION](LINK.png)
      render: Markdown
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/misyaguziya/VRCT/blob/master/LICENSE)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true